import dimensional_analysis_similarity_applied_problems_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace dimensional_analysis_similarity_applied_problems_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end dimensional_analysis_similarity_applied_problems_theorem_canonical_lane_mathlib
end HautevilleHouse
